/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	che_eclipse_org_v1 "github.com/skabashnyuk/kubsrv/pkg/api/che.eclipse.org/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCheFeatures implements CheFeatureInterface
type FakeCheFeatures struct {
	Fake *FakeCheV1
	ns   string
}

var chefeaturesResource = schema.GroupVersionResource{Group: "che.eclipse.org", Version: "v1", Resource: "chefeatures"}

var chefeaturesKind = schema.GroupVersionKind{Group: "che.eclipse.org", Version: "v1", Kind: "CheFeature"}

// Get takes name of the cheFeature, and returns the corresponding cheFeature object, and an error if there is any.
func (c *FakeCheFeatures) Get(name string, options v1.GetOptions) (result *che_eclipse_org_v1.CheFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(chefeaturesResource, c.ns, name), &che_eclipse_org_v1.CheFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheFeature), err
}

// List takes label and field selectors, and returns the list of CheFeatures that match those selectors.
func (c *FakeCheFeatures) List(opts v1.ListOptions) (result *che_eclipse_org_v1.CheFeatureList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(chefeaturesResource, chefeaturesKind, c.ns, opts), &che_eclipse_org_v1.CheFeatureList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &che_eclipse_org_v1.CheFeatureList{}
	for _, item := range obj.(*che_eclipse_org_v1.CheFeatureList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cheFeatures.
func (c *FakeCheFeatures) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(chefeaturesResource, c.ns, opts))

}

// Create takes the representation of a cheFeature and creates it.  Returns the server's representation of the cheFeature, and an error, if there is any.
func (c *FakeCheFeatures) Create(cheFeature *che_eclipse_org_v1.CheFeature) (result *che_eclipse_org_v1.CheFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(chefeaturesResource, c.ns, cheFeature), &che_eclipse_org_v1.CheFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheFeature), err
}

// Update takes the representation of a cheFeature and updates it. Returns the server's representation of the cheFeature, and an error, if there is any.
func (c *FakeCheFeatures) Update(cheFeature *che_eclipse_org_v1.CheFeature) (result *che_eclipse_org_v1.CheFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(chefeaturesResource, c.ns, cheFeature), &che_eclipse_org_v1.CheFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheFeature), err
}

// Delete takes name of the cheFeature and deletes it. Returns an error if one occurs.
func (c *FakeCheFeatures) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(chefeaturesResource, c.ns, name), &che_eclipse_org_v1.CheFeature{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCheFeatures) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(chefeaturesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &che_eclipse_org_v1.CheFeatureList{})
	return err
}

// Patch applies the patch and returns the patched cheFeature.
func (c *FakeCheFeatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *che_eclipse_org_v1.CheFeature, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(chefeaturesResource, c.ns, name, data, subresources...), &che_eclipse_org_v1.CheFeature{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheFeature), err
}
