/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	che_eclipse_org_v1 "github.com/skabashnyuk/kubsrv/pkg/api/che.eclipse.org/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCheServices implements CheServiceInterface
type FakeCheServices struct {
	Fake *FakeCheV1
	ns   string
}

var cheservicesResource = schema.GroupVersionResource{Group: "che.eclipse.org", Version: "v1", Resource: "cheservices"}

var cheservicesKind = schema.GroupVersionKind{Group: "che.eclipse.org", Version: "v1", Kind: "CheService"}

// Get takes name of the cheService, and returns the corresponding cheService object, and an error if there is any.
func (c *FakeCheServices) Get(name string, options v1.GetOptions) (result *che_eclipse_org_v1.CheService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cheservicesResource, c.ns, name), &che_eclipse_org_v1.CheService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheService), err
}

// List takes label and field selectors, and returns the list of CheServices that match those selectors.
func (c *FakeCheServices) List(opts v1.ListOptions) (result *che_eclipse_org_v1.CheServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cheservicesResource, cheservicesKind, c.ns, opts), &che_eclipse_org_v1.CheServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &che_eclipse_org_v1.CheServiceList{}
	for _, item := range obj.(*che_eclipse_org_v1.CheServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cheServices.
func (c *FakeCheServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cheservicesResource, c.ns, opts))

}

// Create takes the representation of a cheService and creates it.  Returns the server's representation of the cheService, and an error, if there is any.
func (c *FakeCheServices) Create(cheService *che_eclipse_org_v1.CheService) (result *che_eclipse_org_v1.CheService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cheservicesResource, c.ns, cheService), &che_eclipse_org_v1.CheService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheService), err
}

// Update takes the representation of a cheService and updates it. Returns the server's representation of the cheService, and an error, if there is any.
func (c *FakeCheServices) Update(cheService *che_eclipse_org_v1.CheService) (result *che_eclipse_org_v1.CheService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cheservicesResource, c.ns, cheService), &che_eclipse_org_v1.CheService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheService), err
}

// Delete takes name of the cheService and deletes it. Returns an error if one occurs.
func (c *FakeCheServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(cheservicesResource, c.ns, name), &che_eclipse_org_v1.CheService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCheServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cheservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &che_eclipse_org_v1.CheServiceList{})
	return err
}

// Patch applies the patch and returns the patched cheService.
func (c *FakeCheServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *che_eclipse_org_v1.CheService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cheservicesResource, c.ns, name, data, subresources...), &che_eclipse_org_v1.CheService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*che_eclipse_org_v1.CheService), err
}
