/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/skabashnyuk/kubsrv/pkg/api/che.eclipse.org/v1"
	scheme "github.com/skabashnyuk/kubsrv/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CheFeaturesGetter has a method to return a CheFeatureInterface.
// A group's client should implement this interface.
type CheFeaturesGetter interface {
	CheFeatures(namespace string) CheFeatureInterface
}

// CheFeatureInterface has methods to work with CheFeature resources.
type CheFeatureInterface interface {
	Create(*v1.CheFeature) (*v1.CheFeature, error)
	Update(*v1.CheFeature) (*v1.CheFeature, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.CheFeature, error)
	List(opts meta_v1.ListOptions) (*v1.CheFeatureList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CheFeature, err error)
	CheFeatureExpansion
}

// cheFeatures implements CheFeatureInterface
type cheFeatures struct {
	client rest.Interface
	ns     string
}

// newCheFeatures returns a CheFeatures
func newCheFeatures(c *CheV1Client, namespace string) *cheFeatures {
	return &cheFeatures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cheFeature, and returns the corresponding cheFeature object, and an error if there is any.
func (c *cheFeatures) Get(name string, options meta_v1.GetOptions) (result *v1.CheFeature, err error) {
	result = &v1.CheFeature{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chefeatures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CheFeatures that match those selectors.
func (c *cheFeatures) List(opts meta_v1.ListOptions) (result *v1.CheFeatureList, err error) {
	result = &v1.CheFeatureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("chefeatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cheFeatures.
func (c *cheFeatures) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("chefeatures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cheFeature and creates it.  Returns the server's representation of the cheFeature, and an error, if there is any.
func (c *cheFeatures) Create(cheFeature *v1.CheFeature) (result *v1.CheFeature, err error) {
	result = &v1.CheFeature{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("chefeatures").
		Body(cheFeature).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cheFeature and updates it. Returns the server's representation of the cheFeature, and an error, if there is any.
func (c *cheFeatures) Update(cheFeature *v1.CheFeature) (result *v1.CheFeature, err error) {
	result = &v1.CheFeature{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("chefeatures").
		Name(cheFeature.Name).
		Body(cheFeature).
		Do().
		Into(result)
	return
}

// Delete takes name of the cheFeature and deletes it. Returns an error if one occurs.
func (c *cheFeatures) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chefeatures").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cheFeatures) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("chefeatures").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cheFeature.
func (c *cheFeatures) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CheFeature, err error) {
	result = &v1.CheFeature{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("chefeatures").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
