/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/skabashnyuk/kubsrv/pkg/api/che.eclipse.org/v1"
	scheme "github.com/skabashnyuk/kubsrv/pkg/client/clientset/versioned/scheme"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CheServicesGetter has a method to return a CheServiceInterface.
// A group's client should implement this interface.
type CheServicesGetter interface {
	CheServices(namespace string) CheServiceInterface
}

// CheServiceInterface has methods to work with CheService resources.
type CheServiceInterface interface {
	Create(*v1.CheService) (*v1.CheService, error)
	Update(*v1.CheService) (*v1.CheService, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.CheService, error)
	List(opts meta_v1.ListOptions) (*v1.CheServiceList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CheService, err error)
	CheServiceExpansion
}

// cheServices implements CheServiceInterface
type cheServices struct {
	client rest.Interface
	ns     string
}

// newCheServices returns a CheServices
func newCheServices(c *CheV1Client, namespace string) *cheServices {
	return &cheServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cheService, and returns the corresponding cheService object, and an error if there is any.
func (c *cheServices) Get(name string, options meta_v1.GetOptions) (result *v1.CheService, err error) {
	result = &v1.CheService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cheservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CheServices that match those selectors.
func (c *cheServices) List(opts meta_v1.ListOptions) (result *v1.CheServiceList, err error) {
	result = &v1.CheServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("cheservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cheServices.
func (c *cheServices) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("cheservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cheService and creates it.  Returns the server's representation of the cheService, and an error, if there is any.
func (c *cheServices) Create(cheService *v1.CheService) (result *v1.CheService, err error) {
	result = &v1.CheService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("cheservices").
		Body(cheService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cheService and updates it. Returns the server's representation of the cheService, and an error, if there is any.
func (c *cheServices) Update(cheService *v1.CheService) (result *v1.CheService, err error) {
	result = &v1.CheService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("cheservices").
		Name(cheService.Name).
		Body(cheService).
		Do().
		Into(result)
	return
}

// Delete takes name of the cheService and deletes it. Returns an error if one occurs.
func (c *cheServices) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cheservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cheServices) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("cheservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cheService.
func (c *cheServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CheService, err error) {
	result = &v1.CheService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("cheservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
